server.port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core-service-api-route
          uri: lb://CORE-SERVICE-API
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: taxriskfed-route
          uri: lb://taxriskfed
          predicates:
            - Path=/TaxRiskApp/**
        - id: PortalService-route
          uri: lb://PortalService
          predicates:
            - Path=/iBizPortal/**

eureka:
  client:
    service-url:
      defaultZone: http://zj-laptop-work:8761/eureka/